[package]
name = "fast_read_optimizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io-uring = "0.5"
iou = "0.3.3"
libc = "0.2.137"
memmem = "0.1.1"
rand = "0.8.5"
