use super::CommandHelp;

pub(super) fn command_help(name: &str) -> Option<CommandHelp> {
    match name {
        "read" => Some(CommandHelp {
            name: "read",
            usage: "read [--auto-lift] [--to-memory] [--paged-shared-buffer|--mmap|--mmap-read-pages|--multiple-target-buffers] [--threads N] [--qd N] [--blocksize SIZE] [--disable-hugepages] [--measure-unmap-time] [--auto|--no-direct|--direct] [-v] [-n iterations] [-s] [-c config.json] <filename>",
            summary: "Striped multi-threaded file read for measuring raw throughput on one file.",
            notes: &[
                "Use -n 1 for one measured run with the current tuned parameters.",
                "Use -s together with --direct or --no-direct to save the best result back to config.",
                "With --direct, fro prints one stderr warning if a non-terminal requested direct read falls back to page cache because O_DIRECT open failed or a mid-file range was unaligned.",
                "--auto-lift starts cold files on the direct path while a background thread warms the page cache for later iterations in the same process.",
                "--to-memory defaults to an auto backend: mmap when both the first and last pages look cached, otherwise the direct/shared-buffer loader.",
                "--paged-shared-buffer forces the old shared destination-buffer loader for read --to-memory.",
                "--mmap maps the file instead of reading into a destination buffer; --mmap-read-pages also walks the mapped bytes in userspace.",
                "--multiple-target-buffers gives each reader thread its own destination buffer with no consolidation step.",
                "--to-memory uses hugepage advice automatically for files >= 64 MiB; smaller files default to non-hugepages. --disable-hugepages turns advice off entirely for the mapped or destination buffer backing.",
                "--measure-unmap-time keeps mmap teardown inside the timed region for --mmap and --mmap-read-pages.",
                "--threads, --qd, and --blocksize override the read-side tuned params so you can do one-off perf sweeps without editing fro.json.",
            ],
            examples: &[
                (
                    "Measure direct-IO read throughput once",
                    "read --direct -n 1 /mnt/fast/bigfile.dat",
                ),
                (
                    "Let read --to-memory auto-pick mmap vs direct based on cache state",
                    "read --to-memory -n 1 /mnt/fast/bigfile.dat",
                ),
                (
                    "Start cold reads on direct IO, then flip later iterations onto page cache",
                    "read --auto-lift -n 100 /mnt/fast/bigfile.dat",
                ),
                (
                    "Map a hot file and read all mapped bytes",
                    "read --to-memory --mmap-read-pages --no-direct -n 1 /mnt/fast/bigfile.dat",
                ),
            ],
        }),
        "grep" => Some(CommandHelp {
            name: "grep",
            usage: "grep [--auto-lift] [--auto|--no-direct|--direct] [-v] [-n iterations] [-s] [-c config.json] <pattern> <filename>",
            summary: "Read plus literal byte-substring search over one file.",
            notes: &[
                "This is a literal substring search, not a regex engine.",
                "Matches are printed as offset:pattern.",
                "With --direct, fro prints one stderr warning if any requested direct scan falls back to page cache because O_DIRECT open failed or a tail request was unaligned.",
                "--auto-lift starts cold files on the direct path while a background thread warms the page cache for later iterations in the same process.",
            ],
            examples: &[
                (
                    "Scan a file in page cache for a literal marker string",
                    "grep --no-direct -n 1 needle /mnt/fast/bigfile.dat",
                ),
                (
                    "Start cold and improve over repeated scans of the same file",
                    "grep --auto-lift -n 100 needle /mnt/fast/bigfile.dat",
                ),
            ],
        }),
        "config" => Some(CommandHelp {
            name: "config",
            usage: "config <print|explain> [--for <path>] [-c config.json]",
            summary: "Print raw config or explain the effective config chosen for one path.",
            notes: &[
                "config print emits the currently loaded config file as JSON.",
                "config explain shows defaults, matching mount info, extracted device signature details, any matched device-db profile, any mount override, and the effective config after applying device-db params and then mount overrides.",
                "The --for path is resolved the same way runtime path-based config selection resolves mount and device context for I/O decisions.",
                "fro-optimize --for <path> uses the same mount selection rule when deciding which mount_overrides entry to write.",
            ],
            examples: &[
                ("Print the active config file", "config print"),
                (
                    "Explain config selection for a file on a specific mount",
                    "config explain --for /mnt/nvme/data.bin",
                ),
                (
                    "Explain config selection using an explicit config file",
                    "config explain -c fro.json --for ./target/test.bin",
                ),
            ],
        }),
        "cat" => Some(CommandHelp {
            name: "cat",
            usage: "cat [--auto|--no-direct|--direct] [--report-gbps] <file> [file ...]",
            summary: "Print one or more files using fro's fast read path.",
            notes: &[
                "Useful as a compatibility wrapper over the same IO-mode flags as fro reads.",
                "--report-gbps writes effective input throughput to stderr after the payload finishes.",
                "--help shows this message and exits.",
                "--version prints the fro cat version string and exits.",
            ],
            examples: &[("Print two files", "cat a.txt b.txt")],
        }),
        "rm" => Some(CommandHelp {
            name: "rm",
            usage: "rm [-f] [-i|-I|--interactive[=WHEN]] [--one-file-system] [--preserve-root|--no-preserve-root] [-d] [-r|-R|--recursive] [-v] <file> [file ...]",
            summary: "Remove files or directory trees, with recursive delete using fro's tree-walk plumbing.",
            notes: &[
                "-d/--dir removes empty directories without switching to the recursive tree-walk path.",
                "-f/--force ignores missing operands and missing files, matching the common cleanup flow.",
                "-i, -I, and --interactive[=WHEN] add bounded GNU-like prompting; the last conflicting prompt flag wins.",
                "--one-file-system only constrains recursive descent; prompt ordering and preserve-root handling stay unchanged.",
                "--preserve-root (the default) refuses recursive removal of '/'; --no-preserve-root disables that failsafe.",
                "Recursive removal uses the existing tree-delete helper; plain file removal stays on the simple unlink path.",
                "--help shows this message and exits.",
                "--version prints the fro rm version string and exits.",
            ],
            examples: &[
                ("Ignore cache-cleanup misses", "rm -f build/output.bin"),
                ("Remove a directory tree verbosely", "rm -rv scratch-tree"),
            ],
        }),
        "mv" => Some(CommandHelp {
            name: "mv",
            usage: "mv [--strip-trailing-slashes] [-b|--backup] [-S SUFFIX|--suffix=SUFFIX] [-f|--force] [-i|--interactive] [-n|--no-clobber] [-u|--update] [-v|--verbose] [-T|--no-target-directory] [-t DIRECTORY|--target-directory=DIRECTORY] <source>... <target>",
            summary: "Rename files or move them into a directory, with cross-filesystem fallback via fro copy helpers.",
            notes: &[
                "Same-filesystem moves use rename(2) when possible.",
                "Cross-filesystem file and directory moves fall back to the fro copy/remove path.",
                "-b/--backup renames an overwritten destination to DEST~ before reusing the existing rename or copy/remove backend.",
                "-S/--suffix customizes the simple backup suffix and implies backup mode for the same GNU-style workflow.",
                "-f/--force keeps the default overwrite-on-conflict behavior; the last conflicting overwrite-policy flag wins.",
                "-i/--interactive prompts before overwriting an existing destination; the last conflicting overwrite-policy flag wins.",
                "-n/--no-clobber skips an existing destination without touching the fast rename or copy/remove backends.",
                "--strip-trailing-slashes trims trailing '/' bytes from source operands before dispatch, matching GNU mv without changing the existing rename or copy/remove backend selection.",
                "-u/--update only replaces a destination when the source entry is newer than the existing target.",
                "-T/--no-target-directory treats the destination as a path, matching GNU mv.",
                "-Z/--context remain unsupported in this bounded slice; fro does not implement SELinux context preservation or relabeling for mv.",
                "--help shows this message and exits.",
                "--version prints the fro mv version string and exits.",
            ],
            examples: &[
                ("Rename one file", "mv old.bin new.bin"),
                ("Move multiple files into a directory", "mv a.bin b.bin archive/"),
                ("Move files into a specific directory", "mv -t archive/ a.bin b.bin"),
            ],
        }),
        "base64" => Some(CommandHelp {
            name: "base64",
            usage: "base64 [-d|--decode] [-i|--ignore-garbage] [-w cols|--wrap=cols] [--auto|--no-direct|--direct] [--report-gbps] [file]",
            summary: "Encode or decode one file or stdin using RFC 4648 base64.",
            notes: &[
                "Without a file operand, or when the file is -, base64 reads standard input.",
                "Encoding wraps at 76 columns by default; use -w 0 to disable wrapping.",
                "--ignore-garbage only affects decode mode.",
                "--report-gbps writes effective input throughput to stderr after processing.",
                "--help shows this message and exits.",
                "--version prints the fro base64 version string and exits.",
            ],
            examples: &[
                ("Encode stdin without wrapping", "base64 -w 0 < input.bin"),
                ("Decode one file", "base64 -d payload.b64"),
            ],
        }),
        "gzip" => Some(CommandHelp {
            name: "gzip",
            usage: "gzip [-d] [-c] [-k] [-f] [-1..-9] [--threads N] [-o FILE|--output=FILE] [--auto|--no-direct|--direct] [--report-gbps] [file]",
            summary: "Experimental gzip-compatible compressor/decompressor using mgzip output plus an optional rapidgzip generic decode path.",
            notes: &[
                "This bounded slice focuses on one input at a time, fast file decompression, and basic gzip/gunzip/zcat flows instead of full GNU gzip parity.",
                "Compression writes mgzip-compatible gzip members via gzp; mgzip decompression uses gzp's parallel mgzip reader.",
                "When built with the optional rapidgzip-backend feature, regular generic .gz file decompression uses rapidgzip; otherwise, and for stdin-backed generic gzip input, fro falls back to the standard multi-member gzip reader.",
                "Regular-file compression inputs use fro's ordered block visitor; regular-file decompression outputs use fro's buffered file writer.",
                "--auto/--no-direct/--direct currently affect the compression-side fro input path only; decompression does not yet route compressed-input reads through fro's direct/page-cache selectors.",
                "Without -c/--stdout or -o/--output, gzip writes FILE.gz, gunzip writes FILE with a .gz suffix stripped, and default in-place conversions remove the source unless -k is used.",
                "--report-gbps reports compression throughput in uncompressed input bytes/s and decompression throughput in emitted output bytes/s.",
            ],
            examples: &[
                ("Compress one file in place", "gzip payload.bin"),
                ("Keep the source and write an explicit archive", "gzip -k -o payload.bin.gz payload.bin"),
                ("Decompress one archive into a named file", "gzip -d -k -o payload.bin payload.bin.gz"),
                ("Stream decompressed output to stdout", "gzip -dc payload.bin.gz"),
            ],
        }),
        "gunzip" => Some(CommandHelp {
            name: "gunzip",
            usage: "gunzip [-c] [-k] [-f] [--threads N] [-o FILE|--output=FILE] [--auto|--no-direct|--direct] [--report-gbps] [file.gz]",
            summary: "Experimental gzip-compatible decompressor alias with mgzip fast-path support and optional rapidgzip generic file decode.",
            notes: &[
                "gunzip is the same bounded experimental implementation as gzip -d.",
                "Regular-file outputs use fro's buffered writer; mgzip streams use gzp's parallel mgzip decompressor.",
                "Generic file-backed gzip inputs use rapidgzip only when fro is built with the optional rapidgzip-backend feature; other generic gzip inputs fall back to the standard reader.",
                "--auto/--no-direct/--direct are currently compression-side flags and do not retune decompression input reads.",
            ],
            examples: &[
                ("Decompress one archive in place", "gunzip payload.bin.gz"),
                ("Keep the source and write to stdout", "gunzip -ck payload.bin.gz"),
            ],
        }),
        "zcat" => Some(CommandHelp {
            name: "zcat",
            usage: "zcat [--threads N] [--auto|--no-direct|--direct] [--report-gbps] [file.gz]",
            summary: "Experimental gzip-compatible stdout decompressor alias with mgzip fast-path support and optional rapidgzip generic file decode.",
            notes: &[
                "zcat is equivalent to the bounded experimental gzip -dc path.",
                "Generic file-backed gzip inputs use rapidgzip only when fro is built with the optional rapidgzip-backend feature.",
                "It keeps the input file and always writes decompressed bytes to stdout.",
            ],
            examples: &[("Print one archive", "zcat payload.bin.gz")],
        }),
        "encrypt" => Some(CommandHelp {
            name: "encrypt",
            usage: "encrypt --passphrase-file PATH [--cipher NAME] [-o file] [input]",
            summary: "Encrypt data into OpenSSL-compatible aes-256-ctr output via the OpenSSL library.",
            notes: &[
                "Regular-file inputs are processed in parallel 512 KiB blocks.",
                "Only aes-256-ctr is supported, derived with PBKDF2-HMAC-SHA256 and the standard `Salted__` header.",
                "No trailing b3sum is appended because extra bytes would break `openssl enc` compatibility.",
                "aes-256-ctr is unauthenticated, so wrong-passphrase decrypts may return garbage rather than a hard error.",
                "Use -o/--output to write to a file; otherwise ciphertext is written to stdout.",
            ],
            examples: &[
                (
                    "Encrypt one file into a sibling output file",
                    "encrypt --passphrase-file secret.txt -o payload.enc payload.bin",
                ),
                (
                    "Encrypt stdin to stdout with the supported cipher",
                    "encrypt --passphrase-file secret.txt --cipher aes-256-ctr < payload.bin > payload.enc",
                ),
            ],
        }),
        "decrypt" => Some(CommandHelp {
            name: "decrypt",
            usage: "decrypt --passphrase-file PATH [--cipher NAME] [-o file] [input]",
            summary: "Decrypt OpenSSL-compatible aes-256-ctr ciphertext in-process.",
            notes: &[
                "Regular-file inputs are processed in parallel 512 KiB blocks.",
                "Only aes-256-ctr with the OpenSSL `Salted__` header and PBKDF2-HMAC-SHA256 derivation is supported.",
                "Ciphertext must match the bytes produced by `fro encrypt` or `openssl enc -aes-256-ctr -pbkdf2 -salt`.",
            ],
            examples: &[
                (
                    "Decrypt a file to stdout",
                    "decrypt --passphrase-file secret.txt payload.enc > payload.bin",
                ),
                (
                    "Decrypt into a named output file",
                    "decrypt --passphrase-file secret.txt -o payload.bin payload.enc",
                ),
            ],
        }),
        "cmp" => Some(CommandHelp {
            name: "cmp",
            usage: "cmp [-r|-R|--recursive] [--auto|--no-direct|--direct] [--report-gbps] [--] <file1> <file2>",
            summary: "Compare two files using fro's diff engine and GNU cmp-style reporting.",
            notes: &[
                "Exits nonzero on mismatch or size difference.",
                "-r/-R/--recursive compares two directory trees in sorted name order and reuses cmp-style file reporting for matching child files.",
                "--help shows this message and exits.",
                "-v/--version prints the fro cmp version string and exits.",
                "--report-gbps writes effective compared-input throughput to stderr after successful full comparisons.",
            ],
            examples: &[
                ("Compare two files", "cmp a.bin b.bin"),
                ("Compare two directory trees", "cmp -r tree-a tree-b"),
            ],
        }),
        "fgrep" => Some(CommandHelp {
            name: "fgrep",
            usage: "fgrep [-n] [-i] [-x] [-v] [-e PATTERN | -f FILE]... [--no-ignore-case] [--auto|--no-direct|--direct] [--report-gbps] [pattern] <file> [file ...]",
            summary: "Bounded literal line-oriented grep slice on top of fro's fast substring scanner.",
            notes: &[
                "This is a bounded literal-search compatibility slice, not full GNU grep.",
                "The in-process path only covers literal line selection over explicit files or stdin: -F/--fixed-strings, -n/--line-number, -x/--line-regexp, -i/--ignore-case, --no-ignore-case, -c/--count, -v/--invert-match, -e/--regexp, -f/--file, --help, and --version.",
                "-i/--ignore-case folds ASCII case for literal matching; --no-ignore-case turns it back off.",
                "-v/--invert-match selects non-matching lines while keeping the same literal matcher.",
                "-e/--regexp and -f/--file can be repeated; if neither is provided, the first positional argument is the pattern.",
                "Regex/search-mode families (-E/-G/-P), recursive include/exclude traversal (-r/-R/--include/--exclude*), context/output shaping (-A/-B/-C/-m/-o/-H/-h/-b/-T/-Z/--color/--colour), and binary/device handling (-a/-I/-U/-d/-D/-z/...) stay outside this slice.",
                "Unsupported GNU grep tokens are documented in COMPAT below; they are not promised by fro's in-process fgrep, though compatibility fallback may still hand some unsupported invocations to external tools when enabled.",
                "--report-gbps writes effective scanned-input throughput to stderr.",
                "--help shows this message and exits.",
                "--version prints the fro fgrep version string and exits.",
            ],
            examples: &[
                ("Print matching lines with numbers", "fgrep -n needle notes.txt"),
                ("Match any listed pattern file entry", "fgrep -f patterns.txt notes.txt"),
                ("Match literally without ASCII case sensitivity", "fgrep -i needle notes.txt"),
                ("Match whole lines literally", "fgrep -x needle notes.txt"),
                ("Print lines that do not contain the literal", "fgrep -v needle notes.txt"),
            ],
        }),
        "find" => Some(CommandHelp {
            name: "find",
            usage: "find [path ...] [-maxdepth N] [-type TYPE] [-name PATTERN|-iname PATTERN] [-path PATTERN|-ipath PATTERN] [-print|-print0]",
            summary: "Walk one or more directory trees with a bounded GNU find-compatible predicate slice.",
            notes: &[
                "This is a bounded GNU find-compatible path-walking/predicate slice, not the full GNU find expression language.",
                "Supported in-process families are limited to roots, -maxdepth, -type, -name/-iname, -path/-ipath, and -print/-print0.",
                "Supported selector families combine as a bounded implicit AND; GNU boolean operators, parentheses, alternate actions, traversal modes, and metadata/time predicates are intentionally omitted here and listed in COMPAT below.",
                "The current walker keeps its existing no-follow behavior; fro does not expose GNU -P/-H/-L symlink-mode switches in this slice.",
                "This correctness slice does not guarantee output ordering.",
                "-maxdepth limits descent below each starting path while still printing matching roots.",
                "-type supports the common GNU/POSIX letters b, c, d, p, f, l, and s.",
                "-name matches only the final path component using shell glob syntax.",
                "-iname matches basenames case-insensitively using shell glob syntax.",
                "-path matches the whole emitted path using shell glob syntax.",
                "-ipath matches whole emitted paths case-insensitively using shell glob syntax.",
                "-print is the default action; -print0 emits NUL-delimited paths for xargs -0 style pipelines.",
                "--help shows this message and exits.",
                "--version prints the fro find version string and exits.",
            ],
            examples: &[
                ("Walk the current tree", "find ."),
                ("Stay at the top level", "find src -maxdepth 1"),
                ("Walk two roots", "find src tests"),
                ("List only regular files", "find . -type f"),
                ("Match Rust sources by basename", "find src -name '*.rs'"),
                ("Match Rust sources case-insensitively", "find src -iname '*.RS'"),
                ("Match a subtree by emitted path", "find . -path '*/target/*'"),
                ("Match a subtree case-insensitively", "find . -ipath '*/TARGET/*'"),
                ("Emit NUL-delimited directory paths", "find src -type d -print0"),
            ],
        }),
        "du" => Some(CommandHelp {
            name: "du",
            usage: "du [-0] [-s] [-a] [-c] [-S] [-b|--bytes] [-k] [-m] [-h|--human-readable|--si] [--apparent-size] [-H|-D|--dereference-args] [-L|--dereference] [-P|--no-dereference] [-B SIZE|--block-size=SIZE] [-d depth|--max-depth=depth] [-t SIZE|--threshold=SIZE] [--] [path ...]",
            summary: "Bounded GNU du-compatible disk-usage accounting for files and directory trees.",
            notes: &[
                "This is a bounded GNU du-compatible accounting/traversal slice, not full GNU du.",
                "Supported families in this slice are output framing and rollups (-0/--null, -s/--summarize, -a/--all, -c/--total, -S/--separate-dirs), size accounting/display (-b/--bytes, --apparent-size, -k, -m, -h/--human-readable, --si, -B/--block-size=SIZE), symlink policy (-H/-D/--dereference-args, -L/--dereference, -P/--no-dereference), bounded traversal filters (-d/--max-depth and -t/--threshold=SIZE), plus --help, --version, and --.",
                "Omitted GNU du families remain unsupported in this slice: hardlink counting (-l/--count-links), exclude/filter list inputs (--exclude, --exclude-from, -X/--exclude-from, --files0-from), inode/time reporting (--inodes, --time, --time-style), and filesystem-boundary control (-x/--one-file-system).",
                "Without -s, directory arguments print descendant directory totals plus the root total.",
                "-0/--null ends each output record with NUL instead of newline.",
                "-a includes non-directory entries in the output.",
                "-c/--total appends a final grand-total line after all requested roots.",
                "-S/--separate-dirs excludes subdirectory totals from parent directory totals while keeping descendants visible.",
                "--apparent-size switches accounting from allocated filesystem blocks to apparent file sizes.",
                "-b/--bytes is shorthand for --apparent-size plus --block-size=1; later display-size flags still override only the printed unit.",
                "-k and -m match GNU du shorthand for --block-size=1K and --block-size=1M.",
                "-h/--human-readable uses IEC powers of 1024, while --si uses decimal powers of 1000; later size-format flags win.",
                "-H/--dereference-args follows only command-line symlink operands; discovered child symlinks still act like leaf entries unless -L is requested later.",
                "-L/--dereference follows command-line symlink operands and symlinks discovered during traversal; the last of -H, -L, and -P wins.",
                "-P/--no-dereference keeps the GNU default: do not follow symlinks unless -H or -L was requested later.",
                "-B SIZE/--block-size=SIZE rescales printed block counts after filesystem allocation rounding; later -h/--si still override the fixed block size.",
                "-d/--max-depth limits which descendant depths are printed while preserving full subtree totals.",
                "-t SIZE/--threshold=SIZE filters emitted entries by measured usage bytes: positive thresholds keep entries at least SIZE, negative thresholds keep entries at most |SIZE|.",
                "--help shows this message and exits.",
                "--version prints the fro du version string and exits.",
                "-- stops option parsing so paths beginning with '-' are treated as operands.",
            ],
            examples: &[
                ("Summarize one tree", "du -s ."),
                ("Print all entries in src", "du -a src"),
                ("Emit NUL-delimited records", "du -a0 src"),
                ("Exclude child directory totals from each parent", "du -S ."),
                ("Follow one symlink operand into its target tree", "du -aH link-to-tree"),
                ("Follow symlinked descendants during traversal", "du -aL tree-with-links"),
                ("Keep symlink operands as symlinks", "du -P link-to-tree"),
                ("Print exact allocated bytes", "du --block-size=1 build"),
                ("Print in decimal human-readable units", "du --si build"),
                ("Measure sparse files by apparent size", "du -b sparse-image.qcow2"),
                ("Show only top-level directory totals", "du --max-depth=1 ."),
                ("Keep only entries at least 1 MiB", "du -at 1M build"),
            ],
        }),
        "head" => Some(CommandHelp {
            name: "head",
            usage: "head [-n lines|-c bytes] [--lines=lines|--bytes=bytes] [-z|--zero-terminated] [-q|-v] [--auto|--no-direct|--direct] [--report-gbps] <file> [file ...]",
            summary: "Print the first lines or bytes of each input.",
            notes: &[
                "Supports classic head counts including obsolete -NUM and -NUM[bkm][cqvz] forms, plus -NUM \"all but last\" forms for -n/-c.",
                "GNU-style --lines/--bytes long forms are accepted, including the explicit --lines= and --bytes= spellings plus negative counts.",
                "-z/--zero-terminated switches line counting from newline-delimited lines to NUL-delimited records while leaving byte modes unchanged.",
                "Use -q/--quiet/--silent to suppress headers and -v/--verbose to always print them; the last one wins.",
                "--report-gbps writes effective emitted-byte throughput to stderr after payload output completes.",
                "--help shows this message and exits.",
                "--version prints the fro head version string and exits.",
            ],
            examples: &[
                ("Print the first ten lines", "head notes.txt"),
                ("Print all but the last 4 KiB", "head -c -4KiB disk.log"),
            ],
        }),
        "sort" => Some(CommandHelp {
            name: "sort",
            usage: "sort [-b|--ignore-leading-blanks] [-c|--check] [-d|--dictionary-order] [-f|--ignore-case] [-g|--general-numeric-sort] [-h|--human-numeric-sort] [-i|--ignore-nonprinting] [-m|--merge] [-M|--month-sort] [-n|--numeric-sort] [-R|--random-sort] [--random-source=FILE] [--files0-from=FILE] [--batch-size=NMERGE] [--parallel=NUM] [--compress-program=PROG] [--debug] [--sort=WORD] [-k KEY|--key=KEY] [-t SEP|--field-separator=SEP] [-r|--reverse] [-s|--stable] [-S SIZE|--buffer-size=SIZE] [-u|--unique] [-V|--version-sort] [-z|--zero-terminated] [-o FILE|--output=FILE] [-T DIR|--temporary-directory=DIR] [--auto|--no-direct|--direct] [--report-gbps] [--] [file ...]",
            summary: "Sort locale-independent records in ascending byte, numeric, general-numeric, human-numeric, month, random, or version order, using newlines by default and NULs with -z.",
            notes: &[
                "This bounded slice implements the default bytewise newline-delimited case plus bounded -b/-d/-f/-i/-k/-t/--sort=WORD/--ignore-leading-blanks/--dictionary-order/--ignore-case/--ignore-nonprinting/--key/--field-separator field selection, -g/-h/-M/-n/-R/-V compatibility modes, --random-source seeding, --files0-from list expansion, --batch-size external-merge fan-in control, --parallel thread-count override, --compress-program temp-run wrapping, GNU-compatible --debug annotations, -z NUL-terminated input records, merge/check, reverse/stable/unique output, -S buffer sizing, -o output-file writes, and -T spill-directory selection.",
                "Use '-' once to read stdin; repeated '-' operands are rejected instead of pretending to reread stdin.",
                "--files0-from=FILE expands NUL-delimited input paths before the existing sort/merge/check/output pipeline runs and rejects '-' entries because stdin is already being consumed by the list.",
                "--batch-size=NMERGE caps the existing out-of-core merge fan-in for spill runs and -m presorted-input merges; in-memory sorts and packed one-shot sorts ignore it.",
                "--parallel=NUM accepts GNU's positive thread-count syntax and currently bounds only the existing packed regular-file line-build/output helpers.",
                "--compress-program=PROG shells `PROG` while writing spill or merge temp runs and `PROG -d` while reading them back; in-memory sorts ignore it because no temp runs exist.",
                "--debug annotates the part of each line used to sort on stdout, warns about bounded questionable usage on stderr, forces newline-delimited debug output, and is incompatible with -c/-C and -o in this slice like GNU sort.",
                "-o writes after all input has been read, so in-place rewrites like `sort -o file file` stay on the same backend.",
                "-T/--temporary-directory only matters when the out-of-core spill/merge backend actually creates temp files.",
                "-b/--ignore-leading-blanks trims leading spaces and tabs from the selected sort key before the existing compare, merge, check, unique, and output pipeline runs.",
                "-d/--dictionary-order filters each selected key down to spaces, tabs, and ASCII alphanumerics before the existing compare, merge, check, unique, and output pipeline runs.",
                "-f/--ignore-case folds ASCII lowercase bytes to uppercase during key comparison while preserving the existing last-resort whole-line, merge, check, and spill/output pipeline semantics.",
                "-i/--ignore-nonprinting filters each selected key down to printable ASCII bytes before the existing compare, merge, check, unique, and output pipeline runs.",
                "-m/--merge reuses the out-of-core merge backend for inputs that are already sorted in the requested mode.",
                "-s/--stable disables GNU sort's last-resort whole-line tie break and preserves input order for records whose selected sort keys compare equal, while reusing the existing comparator/output backend.",
                "-c/--check validates one input stream and exits 1 on the first disorder; with -u it requires strict key ordering.",
                "-g/--general-numeric-sort compares leading C-locale strtod-style floating-point prefixes, keeping GNU-style nonnumeric/NaN/infinity ordering and the existing sort/spill/check backend.",
                "-h/--human-numeric-sort compares leading decimal prefixes plus an optional K/M/G/T/P/E/Z/Y suffix family, matching GNU sort's suffix-group ordering instead of normalizing across suffixes.",
                "-k/--key accepts one or more blank-separated field ranges in the form F[.C][,F[.C]] and reuses the existing compare modes over the selected slices; per-key modifiers remain unsupported.",
                "-t/--field-separator switches -k/--key field discovery from blank runs to one exact separator byte while preserving the existing compare, merge, check, unique, spill, and output backend.",
                "-S/--buffer-size=SIZE overrides the in-memory spill threshold before the existing out-of-core sort backend takes over; GNU-style percentages use available memory when known.",
                "-M/--month-sort compares the first nonblank three-letter month abbreviation in each line, matching GNU sort's invalid-key and tie-break behavior while keeping the existing sort/spill/check backend.",
                "-n/--numeric-sort compares the leading numeric prefix of each line (optional blanks, optional '-', digits, optional fractional part) and otherwise falls back to bytewise line order unless -s or -u suppresses the last-resort tie break.",
                "-R/--random-sort hashes the selected key with a GNU-style seeded MD5 ordering so identical keys stay adjacent while the existing sort/spill/check backend stays intact.",
                "--random-source=FILE seeds -R/--random-sort from the first 16 bytes of FILE; non-random sorts continue to ignore it.",
                "--sort=WORD reuses the existing -g/-h/-M/-n/-R/-V ordering backends for general-numeric, human-numeric, month, numeric, random, and version words; other WORDs still return an error in this bounded slice.",
                "-V/--version-sort uses GNU/coreutils-style version ordering for mixed text-and-digit records while preserving the same spill, merge, and check backend.",
                "Bytewise in-memory sorting uses a StringZilla argsort fast path; oversized inputs spill sorted runs and merge them back out-of-core.",
                "FIXME: Unsupported GNU sort features currently return an error, including locale collation and per-key modifiers.",
                "--report-gbps writes aggregate input throughput to stderr after sorting completes.",
                "--help shows this message and exits.",
                "--version prints the fro sort version string and exits.",
            ],
            examples: &[
                ("Sort one file to stdout", "sort names.txt"),
                ("Check whether one file is already sorted", "sort -c names.txt"),
                ("Merge two already sorted files", "sort -m a.txt b.txt"),
                ("Sort one file by general numeric prefixes", "sort -g floats.txt"),
                ("Sort one file by human-readable size prefixes", "sort -h sizes.txt"),
                ("Sort one file by leading month names", "sort -M months.txt"),
                ("Sort one file by numeric prefixes", "sort -n scores.txt"),
                ("Shuffle one file reproducibly from a seed file", "sort -R --random-source seed.bin names.txt"),
                ("Sort the files named by a NUL-delimited list", "sort --files0-from=input-list0"),
                ("Compress spill runs through an external filter", "sort --compress-program='gzip -1' -S 64K big.txt"),
                ("Sort one file with version ordering", "sort -V release-tags.txt"),
                ("Sort unique records in reverse byte order", "sort -ru names.txt"),
                ("Rewrite one file in place", "sort -o names.txt names.txt"),
                ("Spill large temporary runs under one directory", "sort -T scratch big.txt"),
                ("Sort one file with page-cache reads forced", "sort --no-direct names.txt"),
            ],
        }),
        "tac" => Some(CommandHelp {
            name: "tac",
            usage: "tac [-b|--before] [-r|--regex] [-s|--separator STRING] [--auto|--no-direct|--direct] [--] [file ...]",
            summary: "Print files with record order reversed within each file.",
            notes: &[
                "Default tac keeps the existing newline-delimited reverse-line path; -s/--separator switches to custom record separators.",
                "-r/--regex treats the separator as a regex searched from the end and -b/--before attaches each separator to the following record.",
                "Use -- to stop option parsing so dash-prefixed paths stay on the same tac data path.",
                "--help shows this message and exits.",
                "--version prints the fro tac version string and exits.",
            ],
            examples: &[
                ("Reverse one file by line", "tac notes.txt"),
                ("Reverse records split by ::", "tac -s '::' notes.txt"),
                (
                    "Treat a dash-prefixed name as an input path",
                    "tac -- --dash-prefixed-name.txt",
                ),
            ],
        }),
        "tail" => Some(CommandHelp {
            name: "tail",
            usage: "tail [-n lines|-c bytes] [--lines lines|--bytes bytes] [--lines=lines|--bytes=bytes] [-z|--zero-terminated] [-q|--quiet|--silent|-v|--verbose] [-f|--follow[=descriptor]|--follow=name|-F] [--retry] [-s secs|--sleep-interval secs] [--pid PID] [--max-unchanged-stats N] [--auto|--no-direct|--direct] [--report-gbps] <file> [file ...]",
            summary: "Print the last lines or bytes of each input.",
            notes: &[
                "Supports classic tail counts including +N start offsets for -n/-c/--lines/--bytes.",
                "-z/--zero-terminated switches line counting from newline-delimited lines to NUL-delimited records while leaving byte modes unchanged.",
                "Use -q/--quiet/--silent to suppress headers and -v/--verbose to always print them; the last one wins.",
                "-f/--follow keeps polling regular files after the initial tail pass; --follow=name tracks the path for log rotation, while the default descriptor mode stays attached to the opened file.",
                "-F expands to --follow=name --retry, --retry keeps reopening files that are temporarily inaccessible, -s/--sleep-interval controls the poll interval, --pid stops following once that process exits, and --max-unchanged-stats controls when name-follow rechecks unchanged files for rotation.",
                "Byte-mode on non-seekable inputs keeps only a bounded trailing window before final output.",
                "--report-gbps writes effective emitted-byte throughput to stderr after payload output completes.",
                "--help shows this message and exits.",
                "--version prints the fro tail version string and exits.",
            ],
            examples: &[
                ("Print the last ten lines", "tail notes.txt"),
                ("Print the last 4 KiB", "tail -c 4KiB disk.log"),
            ],
        }),
        "wc" => Some(CommandHelp {
            name: "wc",
            usage: "wc [-l] [-w] [-m] [-c] [-L] [--lines] [--words] [--chars] [--bytes] [--max-line-length] [--files0-from=F] [--auto|--no-direct|--direct] [--report-gbps] [--] <file> [file ...]",
            summary: "Count lines, words, characters, bytes, and max line length using fro block visitors.",
            notes: &[
                "Without -l/-w/-m/-c/-L, prints lines, words, and bytes.",
                "--lines/--words/--chars/--bytes match the GNU wc long count flags.",
                "--files0-from=F reads NUL-delimited input names from F (or stdin when F is -).",
                "--help shows this message and exits.",
                "--version prints the fro wc version string and exits.",
                "-- stops option parsing so filenames beginning with - are counted as inputs.",
                "--report-gbps writes effective processed-input throughput to stderr.",
            ],
            examples: &[
                ("Count lines and words", "wc -l -w notes.txt"),
                ("Count UTF-8 characters", "wc -m notes.txt"),
                ("Print the maximum display width", "wc -L notes.txt"),
                ("Read NUL-delimited paths from a list file", "wc --files0-from=list0"),
            ],
        }),
        "dd" => Some(CommandHelp {
            name: "dd",
            usage: "dd if=<input> of=<output> [bs=<size>] [count=<blocks>] [skip=<blocks>] [seek=<blocks>] [iflag=direct] [oflag=direct] [conv=notrunc,fsync] [status=none|noxfer|progress]",
            summary: "Copy byte ranges with dd-style operands on top of fro I/O primitives.",
            notes: &[
                "Whole-file copies without offset/count flags use the tuned copy path directly.",
                "Compatibility currently focuses on the covered operands from tests/dd_example_compat.rs.",
                "--help shows this message and exits.",
                "--version prints the fro dd version string and exits.",
            ],
            examples: &[("Copy five 4 KiB blocks with no summary", "dd if=src.bin of=dst.bin bs=4K count=5 status=none")],
        }),
        "tar" => Some(CommandHelp {
            name: "tar",
            usage: "tar [--help|--version] (-c|--create|-t|--list|-x|--extract) (-f|--file <archive.tar[.gz|.tgz|.zst|.zstd]>) [-v|--verbose] [-z|--gzip|--gunzip|--ungzip|-J|--zstd] [<source>... | -C|--directory <dir>]",
            summary: "Bounded GNU tar-compatible create/list/extract slice for ustar archives; .tar.gz/.tgz and .tar.zst/.tar.zstd are supported.",
            notes: &[
                "Supported compatibility slice: create (-c/--create), whole-archive list (-t/--list), and whole-archive extract (-x/--extract) with -f/--file; optional extras in this slice are -v/--verbose, -C/--directory for extract, gzip (-z/--gzip/--gunzip/--ungzip), zstd (-J/--zstd), --help, and --version.",
                "Common bounded short forms include -cf, -czf, -cJf, -tf, -tvf, -xf, -xzf, and -xJf; fro does not claim broader clustered-short GNU tar compatibility beyond the documented whole-archive slice.",
                "Compressed tar supports gzip via -z/--gzip/--gunzip/--ungzip or .tar.gz/.tgz suffixes, and zstd via -J/--zstd or .tar.zst/.tar.zstd/.tzst suffixes.",
                "When built with the optional rapidgzip-backend feature, .tar.gz/.tgz list and extract use rapidgzip for decompression; otherwise they fall back to the standard multi-member gzip reader.",
                "-v/--verbose keeps create-side progress reporting, enables GNU-style verbose output for listing, and prints extracted member names during extract.",
                "FIXME: Extract currently targets regular-file archives, all-member extraction, normal relative paths, and optional -C/--directory destination selection.",
                "FIXME: Compressed create still uses a single tar stream and compressed extraction still does not preserve the uncompressed fast-path copy engine.",
                "FIXME: GNU tar tokens outside this bounded whole-archive slice are acknowledged here as unsupported/omitted notes, not runtime promises. Unsupported create/update/compare families: --append, --catenate, --concatenate, --compare, --delete, --diff, --remove-files, --update, --verify, --occurrence, --restrict, --touch, --get, --append, -A, -d, -r, -u, -W.",
                "FIXME: Unsupported path/member-selection and transform families: --absolute-names, --anchored, --no-anchored, --exclude, --exclude-backups, --exclude-caches, --exclude-caches-all, --exclude-caches-under, --exclude-from, --exclude-ignore, --exclude-ignore-recursive, --exclude-tag, --exclude-tag-all, --exclude-tag-under, --exclude-vcs, --exclude-vcs-ignores, --files-from, --null, --no-null, --recursion, --no-recursion, --starting-file, --starting-file=MEMBER-NAME, --same-order, --strip-components, --to-command, --to-stdout, --transform, --xform, --wildcards, --no-wildcards, --wildcards-match-slash, --no-wildcards-match-slash, --verbatim-files-from, --no-verbatim-files-from, --show-stored-names, --show-transformed-names, --quote-chars, --no-quote-chars, --unquote, --no-unquote, --quoting-style, --quoting-style=escape, --index-file, --block-number, --read-full-records, --warning, --checkpoint, --checkpoint-action, --interactive, --confirmation, --keep-old-files, --keep-newer-files, --skip-old-files, --overwrite, --overwrite-dir, --no-overwrite-dir, --recursive-unlink, --unlink-first, --delay-directory-restore, --no-delay-directory-restore, --keep-directory-symlink, --show-omitted-dirs, --one-top-level, -F, -K, -O, -R, -T, -U, -X, -P, -i, -k, -m, -n, -o, -s, -w.",
                "FIXME: Unsupported compression/format/incremental/tape families: --auto-compress, --no-auto-compress, --bzip2, --compress, --uncompress, --force-local, --format, --format=gnu, --format=posix, --format=v7, --old-archive, --portability, --posix, --pax-option, --pax-option=keyword, --listed-incremental, --incremental, --level, --check-device, --no-check-device, --one-file-system, --check-links, --sparse, --sparse-version, --hole-detection, --sort, --utc, --full-time, --show-defaults, --show-snapshot-field-ranges, --backup, --suffix, --blocking-factor, --record-size, --multi-volume, --tape-length, --volno-file, --new-volume-script, --info-script, --rmt-command, --rmt-command=, --rsh-command, --rsh-command=, --use-compress-program, --files-from, --force-local, --lzma, --lzip, --lzop, --xz, -a, -b, -B, -F, -G, -H, -I, -L, -M, -S, -V, -Z, -g, -j.",
                "FIXME: Unsupported metadata/date/ownership and stdin edge-case families: --acls, --no-acls, --atime-preserve, --clamp-mtime, --after-date, --after-date=DATE-OR-FILE, --newer, --newer-mtime, --newer=DATE-OR-FILE, --mtime, --mtime=DATE-OR-FILE, --mode, --numeric-owner, --owner, --owner-map, --group, --group-map, --same-owner, --no-same-owner, --same-permissions, --no-same-permissions, --preserve-order, --preserve-permissions, --dereference, --hard-dereference, --selinux, --no-selinux, --xattrs, --no-xattrs, --xattrs-exclude, --xattrs-include, --ignore-case, --no-ignore-case, --ignore-command-error, --no-ignore-command-error, --ignore-failed-read, --ignore-zeros, --label, --test-label, --totals, --usage, --show-defaults, --add-file, -f-, -h, -l, -N, -p, --no-seek, --seek.",
            ],
            examples: &[
                ("Archive one directory", "tar -cf tree.tar mytree"),
                ("Archive one directory as gzip", "tar -czf tree.tar.gz mytree"),
                ("List one archive verbosely", "tar -tvf tree.tar"),
                ("Extract one gzip archive into a directory", "tar -xzf tree.tar.gz -C out"),
            ],
        }),
        "shred" => Some(CommandHelp {
            name: "shred",
            usage: "shred [-n/--iterations passes] [-s/--size size] [-z/--zero] [-u/--remove] [-f/--force] [-v/--verbose] [-x/--exact] [--auto|--no-direct|--direct] <file> [file ...]",
            summary: "Overwrite files with random or zero patterns, optionally removing them.",
            notes: &[
                "This bounded GNU-compatible slice covers --iterations, --size, --zero, --remove, --force, --verbose, and --exact.",
                "--exact/-x is accepted as a no-op compatibility alias because fro already overwrites exactly the requested byte count.",
                "--help shows this message and exits.",
                "--version prints the fro shred version string and exits.",
                "--random-source remains unsupported in this slice.",
            ],
            examples: &[
                ("Zero a file once and keep it", "shred --iterations 0 --zero scratch.bin"),
                ("Overwrite only the first 4 KiB verbosely", "shred --iterations 0 --zero --verbose --size 4KiB scratch.bin"),
            ],
        }),
        "write" => Some(CommandHelp {
            name: "write",
            usage: "write [--create <size>] [--auto|--no-direct|--direct] [--auto-write|--no-direct-write|--direct-write] [-v] [-n iterations] [-s] [-c config.json] <filename>",
            summary: "Write a file using the tuned pipeline, optionally creating and sizing it first.",
            notes: &[
                "Without --create, the existing file size is used.",
                "--direct/--no-direct control the read-side planner mode; --direct-write/--no-direct-write control the write side.",
                "With --direct-write, fro prints one stderr warning if any requested direct write falls back to page cache because O_DIRECT open failed or a tail block was unaligned.",
            ],
            examples: &[
                (
                    "Create a fresh 64 MiB file and fill it through the write path",
                    "write --create 64MiB --no-direct -n 1 out.bin",
                ),
                (
                    "Rewrite an existing file with direct writes",
                    "write --direct-write -n 1 out.bin",
                ),
            ],
        }),
        "cp" => Some(CommandHelp {
            name: "cp",
            usage: "cp [-a|-r|-R|--recursive] [-n|-u|-v] [-T|--no-target-directory] [-t DIR|--target-directory=DIRECTORY] [-L|--dereference|-P|--no-dereference] [-p|--preserve|--preserve=mode|--preserve=timestamps|--preserve=mode,timestamps|--preserve=all] [--auto|--no-direct|--direct] [--auto-write|--no-direct-write|--direct-write] <source>... <target>",
            summary: "Bounded GNU cp-compatible alias over fro copy.",
            notes: &[
                "This help surface is intentionally limited to the cp-compatible slice that fro currently implements.",
                "Supported GNU cp flags in this slice: -a/--archive, -r/-R/--recursive, -n/--no-clobber, -u/--update, -v/--verbose, -T/--no-target-directory, -t/--target-directory, -L/--dereference, -P/--no-dereference, -p/--preserve, --preserve=mode, --preserve=timestamps, --preserve=mode,timestamps, and --preserve=all.",
                "--archive maps to recursive copy plus bounded preserve mode/timestamps and --no-dereference; ownership, --preserve=links, SELinux context, and xattrs are not preserved.",
                "--preserve and --preserve=all currently preserve mode and timestamps only; ownership is not preserved, and SELinux context, xattrs, and hardlink preservation are omitted in this bounded slice.",
                "FIXME: GNU cp tokens acknowledged here but not implemented natively in this slice: --backup/-b, --suffix=SUFFIX/-S, --force/-f, --interactive/-i, --link/-l, --symbolic-link/-s, -H, -d, --copy-contents, --one-file-system/-x, --no-preserve=ATTR_LIST, --preserve=links, --context[=CTX]/-Z, --reflink=auto, --reflink=never, --sparse, --sparse=always, --sparse=auto, and --sparse=never.",
                "Other omitted GNU cp compatibility tokens remain unsupported or fallback-only here: --parents, --attributes-only, --remove-destination, and --strip-trailing-slashes.",
                "The alias also accepts fro copy IO-mode selectors: --auto/--no-direct/--direct and --auto-write/--no-direct-write/--direct-write.",
                "Use `fro copy --help` for fro-specific copy-engine controls such as --verify, --verify-diff, --diff, --full, --copy-file-range, --threaded-copy, --reflink, --via-memory, and locking controls.",
                "--help shows this message and exits.",
                "--version prints the fro cp version string and exits.",
            ],
            examples: &[
                ("Copy one file", "cp src.bin dst.bin"),
                (
                    "Recursively copy a tree into an existing destination directory",
                    "cp -r srcdir outdir",
                ),
                (
                    "Preserve mode and timestamps in the bounded cp slice",
                    "cp --preserve=all src.bin dst.bin",
                ),
            ],
        }),
        "copy" | "copy-via-memory" => Some(CommandHelp {
            name: "copy",
            usage: "copy [--recursive|-r|-R] [--via-memory] [--keep-target-size] [--diff|--full] [--copy-file-range|--copy-file-range-single|--threaded-copy|--reflink] [--no-lock] [--verify|--verify-diff] [--hash] [--xxh3|--sha256] [--hash-base path] [-q|--quiet] [--auto|--no-direct|--direct] [--auto-write|--no-direct-write|--direct-write] [-v] [-n iterations] [-s] [-c config.json] <source> <target>",
            summary: "Copy one file, or recursively copy one directory tree, using the tuned read/write pipeline.",
            notes: &[
                "--direct/--no-direct/--auto control source reads.",
                "--direct-write/--no-direct-write/--auto-write control destination writes.",
                "With forced direct read/write flags, fro prints one stderr warning if any source or destination leg falls back to page cache because O_DIRECT open failed or a request tail was unaligned.",
                "--recursive (or -r/-R) enables directory-tree copies; the destination behaves like cp -r, so an existing destination directory receives the source basename as a child.",
                "--copy-file-range uses the tunable multi-call copy_file_range(2) strategy with its own optimizer params.",
                "--copy-file-range-single forces the one-call copy_file_range(2) baseline for benchmarking.",
                "--threaded-copy forces the existing tuned striped io_uring copy path.",
                "--reflink requests a CoW clone/reflink when the filesystem supports it; this is fast but does not promise physically independent storage blocks.",
                "--diff forces chunked diff-and-overwrite copy when supported; --full disables diffing and always rewrites the full file.",
                "Without either flag, plain copy uses the copy auto mode configured in fro.json for the target path; that config can steer copy toward page-cache, direct, copy_file_range, or the cache-aware heuristic path without runtime topology probes.",
                "--keep-target-size preserves an already-sized destination instead of re-truncating/re-preallocating it; this is mainly useful for best-case benchmarking.",
                "Copy takes an advisory shared lock on the source and an advisory exclusive lock on the destination by default; use --no-lock to skip that cooperative locking.",
                "--via-memory loads the whole source file into RAM first, then writes that buffer to the destination.",
                "--verify hashes the source, copies into a temporary sibling, fsyncs and verifies that file, then renames it into place without leaving sidecars by default.",
                "--hash with --verify leaves durable sidecars at the destination and at the source if the source did not already have sidecars, and syncs their parent directories too.",
                "--verify-diff fsyncs the destination and then runs a diff pass instead of block-hash verification.",
                "For non-verified copy modes, fro also checks whether the source file's size/mtime/ctime changed during the operation and fails if it did.",
                "When using --via-memory, tune read and write separately instead of saving copy params.",
                "Verification success is reported to stderr unless --quiet is used.",
                "FIXME: When invoked via the cp multicall alias, the wrapper also understands GNU cp's -a/--archive, -n/--no-clobber, -t/--target-directory, -u/--update, -v/--verbose, -T/--no-target-directory, -L/--dereference, -P/--no-dereference, and preserve compatibility flags: -p/--preserve plus --preserve=mode, --preserve=timestamps, --preserve=mode,timestamps, and --preserve=all, but ownership is not preserved.",
            ],
            examples: &[
                (
                    "Copy in.bin to out.bin",
                    "copy in.bin out.bin",
                ),
                (
                    "Recursively copy a tree into an existing destination directory",
                    "copy --recursive srcdir outdir",
                ),
                (
                    "Read through page cache but force direct writes to the destination",
                    "copy --no-direct --direct-write in.bin out.bin",
                ),
                (
                    "Benchmark the kernel copy_file_range syscall path directly",
                    "copy --copy-file-range-single --no-direct -n 1 in.bin out.bin",
                ),
                (
                    "Optimize the chunked copy_file_range path separately",
                    "copy --copy-file-range --no-direct -n 32 -s in.bin out.bin",
                ),
                (
                    "Force the existing striped io_uring copy path for comparison",
                    "copy --threaded-copy --no-direct -n 1 in.bin out.bin",
                ),
                (
                    "Request a CoW reflink/soft copy when the filesystem supports it",
                    "copy --reflink --no-direct -n 1 in.bin out.bin",
                ),
                (
                    "Load the whole source into RAM, then flush it with direct writes",
                    "copy --via-memory --no-direct --direct-write in.bin out.bin",
                ),
                (
                    "Skip advisory locking when cooperating lock semantics would get in the way",
                    "copy --no-lock --no-direct in.bin out.bin",
                ),
                (
                    "Copy a file through a verified temp target swap without leaving sidecars",
                    "copy --verify --sha256 --no-direct in.bin out.bin",
                ),
                (
                    "Copy a file, verify it, and leave source/destination sidecars",
                    "copy --verify --hash --sha256 --no-direct in.bin out.bin",
                ),
                (
                    "Copy a file and run a diff pass after fsync",
                    "copy --verify-diff --no-direct in.bin out.bin",
                ),
            ],
        }),
        "diff" => Some(CommandHelp {
            name: "diff",
            usage: "diff [--auto|--no-direct|--direct] [-v] [-n iterations] [-s] [-c config.json] <file1> <file2>",
            summary: "Compare two files and report the first mismatch.",
            notes: &["Exits nonzero on mismatch."],
            examples: &[(
                "Check whether two large files are byte-identical",
                "diff --direct a.bin b.bin",
            )],
        }),
        "dual-read-bench" => Some(CommandHelp {
            name: "dual-read-bench",
            usage: "dual-read-bench [--auto|--no-direct|--direct] [-v] [-n iterations] [-s] [-c config.json] <file1> <file2>",
            summary: "Read two files like diff, but treat it as a throughput benchmark rather than a mismatch-reporting tool.",
            notes: &["Useful when you want the read pressure of diff without stopping to explain a mismatch."],
            examples: &[(
                "Benchmark reading two files from page cache",
                "dual-read-bench --no-direct -n 1 a.bin b.bin",
            )],
        }),
        "recursive-read-bench" => Some(CommandHelp {
            name: "recursive-read-bench",
            usage: "recursive-read-bench [--auto|--no-direct|--direct] [-v] <directory>",
            summary: "Read every byte of every regular file in a directory tree and report aggregate throughput.",
            notes: &[
                "This is intended as a read-side roofline for recursive copy/cp measurements.",
                "Symlinks and non-regular files are skipped.",
            ],
            examples: &[(
                "Benchmark the page-cache read roofline of a source tree",
                "recursive-read-bench --no-direct /data/tree",
            )],
        }),
        "file-list-read-bench" => Some(CommandHelp {
            name: "file-list-read-bench",
            usage: "file-list-read-bench [--auto|--no-direct|--direct] [-v] <manifest>",
            summary: "Read every file named in a newline-delimited manifest and report aggregate throughput without tree-walk cost.",
            notes: &[
                "Use this to separate traversal cost from pure many-small-file read throughput.",
                "Each non-empty line in the manifest is treated as one path.",
            ],
            examples: &[(
                "Benchmark reading files listed by a prior find pass",
                "find /data/tree -type f > files.txt && file-list-read-bench --no-direct files.txt",
            )],
        }),
        "file-list-read-uring-bench" => Some(CommandHelp {
            name: "file-list-read-uring-bench",
            usage: "file-list-read-uring-bench [--auto|--no-direct|--direct] [-v] <manifest>",
            summary: "Sweep many-small-file io_uring reads from a manifest using 32 worker threads and varying in-flight file counts.",
            notes: &[
                "Each worker issues separate whole-file reads via its own io_uring.",
                "Sweeps in-flight files per thread over 32, 64, 128, 256, and 512.",
            ],
            examples: &[(
                "Benchmark a many-open-files io_uring approach against a prior find manifest",
                "find /data/tree -type f > files.txt && file-list-read-uring-bench --auto files.txt",
            )],
        }),
        "file-list-read-open-read-close-sweep" => Some(CommandHelp {
            name: "file-list-read-open-read-close-sweep",
            usage: "file-list-read-open-read-close-sweep [--auto|--no-direct|--direct] [-v] <manifest>",
            summary: "Compare open-read-close manifest readers across blocking and io_uring variants over file-count prefixes.",
            notes: &[
                "Runs single-thread, multi-thread, single-thread io_uring, and multi-thread io_uring variants.",
                "Useful for finding the file-count inflection points between reader designs.",
            ],
            examples: &[(
                "Sweep manifest reader variants over small-file prefixes",
                "find /data/tree -type f > files.txt && file-list-read-open-read-close-sweep --auto files.txt",
            )],
        }),
        "manifest-recursive-copy-bench" => Some(CommandHelp {
            name: "manifest-recursive-copy-bench",
            usage: "manifest-recursive-copy-bench [--overlap-large-file PATH] [-v] <manifest> <source_root> <target_root>",
            summary: "Benchmark manifest-driven recursive copy with separate directory-build and file-copy phase timing.",
            notes: &[
                "The manifest must list regular files under <source_root>.",
                "Keep source and target on the same mount when benchmarking the openat+copy_file_range small-file phase.",
                "--overlap-large-file runs one additional large-file copy in parallel with the file-copy phase.",
            ],
            examples: &[(
                "Time recursive copy phases and overlap one large file",
                "manifest-recursive-copy-bench --overlap-large-file /data/ilmari_cache/fro-test/coreutils-1g.bin files.txt /data/tree /data/out",
            )],
        }),
        "split-manifest-recursive-copy-bench" => Some(CommandHelp {
            name: "split-manifest-recursive-copy-bench",
            usage: "split-manifest-recursive-copy-bench [-v] <source_dir> <target_dir>",
            summary: "Benchmark a recursive copy design that first builds the full manifest, then dispatches copy work.",
            notes: &[
                "Uses the same recursive copy lanes as copy --recursive, but delays file-copy dispatch until the full manifest is built.",
                "This exists to compare walk-as-you-go scheduling against a split manifest-build -> dispatch design.",
            ],
            examples: &[(
                "Benchmark split-manifest recursive copy on one tree",
                "split-manifest-recursive-copy-bench /data/tree /data/out",
            )],
        }),
        "bench-recursive-small-file-threads" => Some(CommandHelp {
            name: "bench-recursive-small-file-threads",
            usage: "bench-recursive-small-file-threads [--auto|--no-direct|--direct] [--hot|--cold] [-v] [-s] <directory>",
            summary: "Sweep recursive small-file worker counts for the current cache state and optionally save the per-mount winner.",
            notes: &[
                "The current cache state is inferred from the directory path's first-page residency.",
                "When used with --save, only the hot or cold slot for the current mount is updated.",
            ],
            examples: &[(
                "Tune recursive small-file worker count for the current mount/cache state",
                "bench-recursive-small-file-threads --auto -s /data/tree",
            )],
        }),
        "bench-read-sweep" => Some(CommandHelp {
            name: "bench-read-sweep",
            usage: "bench-read-sweep",
            summary: "Sweep single-file read performance across size buckets for simple ST, ST io_uring, and current MT readers.",
            notes: &[
                "Uses temporary files sized 4 KiB through 256 MiB.",
                "Reports effective GB/s and, when built with the read-phase-timing feature, MT phase timestamps.",
            ],
            examples: &[(
                "Run the reader crossover sweep",
                "bench-read-sweep",
            )],
        }),
        "hash" => Some(CommandHelp {
            name: "hash",
            usage: "hash [--auto|--no-direct|--direct] [--xxh3|--sha256] [--hash-only] [-v] [-n iterations] [-s] [-c config.json] [--hash-base path] <filename>",
            summary: "Hash a file in parallel 1 MiB blocks, hash the hashes, and write three JSON sidecar replicas.",
            notes: &[
                "Default sidecar base is <file>.fro-hash.",
                "Use --xxh3 or --sha256 to choose the sidecar digest algorithm. (NB: this is not sha256sum-compatible.)",
                "Use --hash-only to only print the filename and hash of hashes.",
                "Default -n for hash is 1.",
            ],
            examples: &[(
                "Create block-hash sidecars for one large file",
                "hash --no-direct bigfile.dat",
            ),
            (
                "Get a SHA256 hash of block hashes for easy file comparisons",
                "hash --sha256 --hash-only bigfile.dat",
            )],
        }),
        "verify" => Some(CommandHelp {
            name: "verify",
            usage: "verify [--auto|--no-direct|--direct] [-v] [-n iterations] [-s] [-c config.json] [--hash-base path] <filename>",
            summary: "Re-hash a file, compare it to its sidecars, and report bad blocks.",
            notes: &[
                "Read-only command.",
                "verify follows the hash type stored in the sidecar manifest.",
                "On a clean file with intact sidecars, verify hashes the file once and stops.",
            ],
            examples: &[(
                "Scrub one file against its block-hash sidecars",
                "verify --no-direct bigfile.dat",
            )],
        }),
        "recover" => Some(CommandHelp {
            name: "recover",
            usage: "recover [--auto|--no-direct|--direct] [--fast] [--in-place-all] [-v] [-n iterations] [-s] [-c config.json] [--hash-base path] <target> <copy1> [copy2 ...]",
            summary: "Repair corrupted 1 MiB blocks using one or more full-file replicas.",
            notes: &[
                "Default recover rewrites only the first file; later files are read-only sources.",
                "--fast behaves like verify on the first file unless corruption forces a full multi-file scan.",
                "--in-place-all attempts to repair every input file and refresh broken sidecars.",
                "recover follows each file's stored sidecar hash type.",
            ],
            examples: &[
                (
                    "Repair a target file from one clean copy",
                    "recover --no-direct target.bin backup.bin",
                ),
                (
                    "Use verify-like fast scrub behavior and only fall back to full recovery if needed",
                    "recover --fast --no-direct target.bin backup.bin",
                ),
            ],
        }),
        "bench-diff" => Some(CommandHelp {
            name: "bench-diff",
            usage: "bench-diff",
            summary: "In-memory diff microbenchmark used by the benchmark harness.",
            notes: &["This is mainly for development and regression tracking."],
            examples: &[("Run the in-memory diff microbenchmark", "bench-diff")],
        }),
        "bench-memcpy" => Some(CommandHelp {
            name: "bench-memcpy",
            usage: "bench-memcpy [--size <bytes>] [--threads <count>]",
            summary: "In-memory memcpy microbenchmark for establishing the RAM copy ceiling.",
            notes: &[
                "Defaults to --size 4GiB and --threads 32.",
                "Reports effective bandwidth as source read plus destination write bytes.",
            ],
            examples: &[(
                "Benchmark a 4 GiB to 4 GiB memcpy with 32 threads",
                "bench-memcpy --size 4GiB --threads 32",
            )],
        }),
        "bench-tar-archive" => Some(CommandHelp {
            name: "bench-tar-archive",
            usage: "bench-tar-archive <ram|ram-write|mmap-file> <source-dir> [target-file]",
            summary: "Benchmark tar archive assembly into RAM, RAM+write, or an mmap-backed target file.",
            notes: &[
                "ram: precompute tar offsets, write headers, and copy payload blocks into a preallocated RAM archive buffer.",
                "ram-write: build the tar archive in RAM, then flush it with the existing parallel file-write helpers.",
                "mmap-file: map the output file and write the archive directly into the mapping before msync.",
            ],
            examples: &[
                (
                    "Benchmark tar archive construction into RAM only",
                    "bench-tar-archive ram /data/ilmari_cache/fro-test/tar-mixedbench",
                ),
                (
                    "Benchmark tar archive construction in RAM plus parallel file write",
                    "bench-tar-archive ram-write /data/ilmari_cache/fro-test/tar-mixedbench /data/ilmari_cache/fro-test/tar-mixedbench.tar",
                ),
                (
                    "Benchmark writing the archive directly into an mmap-backed target file",
                    "bench-tar-archive mmap-file /data/ilmari_cache/fro-test/tar-mixedbench /data/ilmari_cache/fro-test/tar-mixedbench.tar",
                ),
            ],
        }),
        "bench-base64-encode" => Some(CommandHelp {
            name: "bench-base64-encode",
            usage: "bench-base64-encode [-n iterations] [--variant auto|scalar|spmd|shuffle]",
            summary: "Hot-loop the in-memory 12 KiB -> 16 KiB base64 encode kernel on one core.",
            notes: &[
                "Uses a fixed 12 KiB source buffer and fixed 16 KiB destination buffer.",
                "Reports iterations per second and effective input GB/s per core.",
                "Use --variant to compare scalar, AVX2 SPMD, and AVX2 shuffle-unpack kernels.",
            ],
            examples: &[(
                "Run one million kernel iterations",
                "bench-base64-encode -n 1000000",
            )],
        }),
        "bench-base64-decode" => Some(CommandHelp {
            name: "bench-base64-decode",
            usage: "bench-base64-decode [-n iterations] [--variant auto|scalar|avx2]",
            summary: "Hot-loop the in-memory 16 KiB -> 12 KiB base64 decode kernel on one core.",
            notes: &[
                "Uses a fixed 16 KiB encoded buffer generated from a fixed 12 KiB source buffer.",
                "Reports iterations per second and effective decoded GB/s per core.",
                "Use --variant to compare scalar and AVX2 decode kernels.",
            ],
            examples: &[(
                "Run one million decode kernel iterations",
                "bench-base64-decode -n 1000000",
            )],
        }),
        "bench-base64-decode-detect-fallback" => Some(CommandHelp {
            name: "bench-base64-decode-detect-fallback",
            usage: "bench-base64-decode-detect-fallback [-n iterations] [--variant auto|scalar|avx2]",
            summary: "Hot-loop decode with a pre-scan that falls back to the wrapped/dirty path when needed.",
            notes: &[
                "Uses clean unwrapped base64 generated from the fixed 12 KiB source buffer.",
                "Measures the cost of checking for garbage/newlines before choosing the fast decode kernel.",
            ],
            examples: &[(
                "Run one million detect+fallback decode iterations",
                "bench-base64-decode-detect-fallback -n 1000000 --variant avx2",
            )],
        }),
        "bench-base64-wrapped-encode" => Some(CommandHelp {
            name: "bench-base64-wrapped-encode",
            usage: "bench-base64-wrapped-encode [-n iterations] [--wrap COLS]",
            summary: "Hot-loop the wrapped base64 encode path on one core.",
            notes: &[
                "Uses the wrapped slow-path implementation over a fixed 12 KiB source buffer.",
                "Reports iterations per second and effective input GB/s per core.",
            ],
            examples: &[(
                "Run one million wrapped encode iterations at 76 columns",
                "bench-base64-wrapped-encode -n 1000000 --wrap 76",
            )],
        }),
        "bench-base64-wrapped-decode" => Some(CommandHelp {
            name: "bench-base64-wrapped-decode",
            usage: "bench-base64-wrapped-decode [-n iterations] [--ignore-garbage]",
            summary: "Hot-loop the wrapped/dirty base64 decode reorganization path on one core.",
            notes: &[
                "Uses wrapped base64 generated from the fixed 12 KiB source buffer.",
                "Reports iterations per second and effective decoded GB/s per core.",
            ],
            examples: &[(
                "Run one million wrapped decode iterations",
                "bench-base64-wrapped-decode -n 1000000",
            )],
        }),
        "bench-mmap-write" => Some(CommandHelp {
            name: "bench-mmap-write",
            usage: "bench-mmap-write <filename>",
            summary: "Memory-mapped write microbenchmark used by the benchmark harness.",
            notes: &[],
            examples: &[(
                "Run the mmap write microbenchmark against an existing file",
                "bench-mmap-write out.bin",
            )],
        }),
        "bench-write" => Some(CommandHelp {
            name: "bench-write",
            usage: "bench-write <filename>",
            summary: "Plain write microbenchmark used by the benchmark harness.",
            notes: &[],
            examples: &[(
                "Run the plain write microbenchmark against an existing file",
                "bench-write out.bin",
            )],
        }),
        _ => None,
    }
}
